# Site settings
title: "Euclid: The Game"
email: "kasperpeulen@gmail.com"
description: "This website tries to gamify The Elements a book written by Euclid."
baseurl: ""
url: "http://euclidthegame.com"

# Defaults
defaults:
    -
        scope:
            path: ""
        values:
            cat: notSorted


# Build settings
markdown: kramdown
permalink: pretty
